import{S as p,i as c}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();function d(o){const s="https://pixabay.com/api/",i="43834463-9b577c35be085229738b1d5bb",r=new URLSearchParams({key:i,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${s}?${r}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const m=o=>o.map(({webformatURL:s,largeImageURL:i,tags:r,likes:e,views:t,comments:n,downloads:u})=>`
      <li class="gallery-item">
            <a class="gallery-link" href="${i}">
                <img class="gallery-img" src="${s}" alt="${r}" />
            </a>
            <div class="gallery-text-container">
                <p class="gallery-text-description"><span>likes</span>${e}</p>
                <p class="gallery-text-description"><span>views</span>${t}</p>
                <p class="gallery-text-description"><span>comments</span> ${n}</p>
                <p class="gallery-text-description"><span>downloads</span>${u}</p>
            </div>
        </li>`).join("");let f=new p(".gallery a",{captionsData:"alt",sourceAttr:"href",captionDelay:250});const h=document.querySelector(".search-form");document.querySelector(".js-search-input");const a=document.querySelector(".js-list"),l=document.querySelector(".loader");h.addEventListener("submit",y);function y(o){o.preventDefault();const i=o.currentTarget.elements.searchKeyword.value.trim();if(i===""){a.innerHTML="",o.target.reset(),c.show({message:"Input field can not be empty",position:"topRight",timeout:2e3,color:"red"});return}a.innerHTML="",l.classList.remove("is-hidden"),d(i).then(r=>{r.total===0&&c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,color:"red"}),a.innerHTML=m(r.hits),f.refresh()}).catch(r=>console.log(r)).finally(()=>{o.target.reset(),l.classList.add("is-hidden")})}
//# sourceMappingURL=commonHelpers.js.map
